name: "Greetings"

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is code owner or collaborator
        id: check_user_role
        run: |
          USER_ROLE=$(jq -r '.sender.site_admin' <<< "$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/collaborators/$(jq -r '.repository.owner.login' <<< "$GITHUB_CONTEXT")/permission)" )
          echo "::set-output name=is_code_owner_or_collaborator::$USER_ROLE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Welcome message for contributors
        if: steps.check_user_role.outputs.is_code_owner_or_collaborator != 'true'
        run: |
          echo "Congratulations, @${{ github.actor }}! 🎉 Thank you for creating an issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!"
